/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiResearchRouteImport } from './routes/api/research'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedFindRouteImport } from './routes/_authenticated/find'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPlacesSearchRouteImport } from './routes/api/places/search'
import { Route as ApiPlacesPhotoRouteImport } from './routes/api/places/photo'
import { Route as ApiPlacesAutocompleteRouteImport } from './routes/api/places/autocomplete'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchRoute = ApiResearchRouteImport.update({
  id: '/api/research',
  path: '/api/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFindRoute = AuthenticatedFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPlacesSearchRoute = ApiPlacesSearchRouteImport.update({
  id: '/api/places/search',
  path: '/api/places/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesPhotoRoute = ApiPlacesPhotoRouteImport.update({
  id: '/api/places/photo',
  path: '/api/places/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacesAutocompleteRoute = ApiPlacesAutocompleteRouteImport.update({
  id: '/api/places/autocomplete',
  path: '/api/places/autocomplete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/find': typeof AuthenticatedFindRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/research': typeof ApiResearchRoute
  '/api/places/autocomplete': typeof ApiPlacesAutocompleteRoute
  '/api/places/photo': typeof ApiPlacesPhotoRoute
  '/api/places/search': typeof ApiPlacesSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/find': typeof AuthenticatedFindRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/research': typeof ApiResearchRoute
  '/api/places/autocomplete': typeof ApiPlacesAutocompleteRoute
  '/api/places/photo': typeof ApiPlacesPhotoRoute
  '/api/places/search': typeof ApiPlacesSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/find': typeof AuthenticatedFindRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/api/research': typeof ApiResearchRoute
  '/api/places/autocomplete': typeof ApiPlacesAutocompleteRoute
  '/api/places/photo': typeof ApiPlacesPhotoRoute
  '/api/places/search': typeof ApiPlacesSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/find'
    | '/outreach'
    | '/saved'
    | '/settings'
    | '/api/assistant'
    | '/api/research'
    | '/api/places/autocomplete'
    | '/api/places/photo'
    | '/api/places/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/find'
    | '/outreach'
    | '/saved'
    | '/settings'
    | '/api/assistant'
    | '/api/research'
    | '/api/places/autocomplete'
    | '/api/places/photo'
    | '/api/places/search'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/find'
    | '/_authenticated/outreach'
    | '/_authenticated/saved'
    | '/_authenticated/settings'
    | '/api/assistant'
    | '/api/research'
    | '/api/places/autocomplete'
    | '/api/places/photo'
    | '/api/places/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAssistantRoute: typeof ApiAssistantRoute
  ApiResearchRoute: typeof ApiResearchRoute
  ApiPlacesAutocompleteRoute: typeof ApiPlacesAutocompleteRoute
  ApiPlacesPhotoRoute: typeof ApiPlacesPhotoRoute
  ApiPlacesSearchRoute: typeof ApiPlacesSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research': {
      id: '/api/research'
      path: '/api/research'
      fullPath: '/api/research'
      preLoaderRoute: typeof ApiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/find': {
      id: '/_authenticated/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof AuthenticatedFindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/places/search': {
      id: '/api/places/search'
      path: '/api/places/search'
      fullPath: '/api/places/search'
      preLoaderRoute: typeof ApiPlacesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/photo': {
      id: '/api/places/photo'
      path: '/api/places/photo'
      fullPath: '/api/places/photo'
      preLoaderRoute: typeof ApiPlacesPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/places/autocomplete': {
      id: '/api/places/autocomplete'
      path: '/api/places/autocomplete'
      fullPath: '/api/places/autocomplete'
      preLoaderRoute: typeof ApiPlacesAutocompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFindRoute: typeof AuthenticatedFindRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFindRoute: AuthenticatedFindRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAssistantRoute: ApiAssistantRoute,
  ApiResearchRoute: ApiResearchRoute,
  ApiPlacesAutocompleteRoute: ApiPlacesAutocompleteRoute,
  ApiPlacesPhotoRoute: ApiPlacesPhotoRoute,
  ApiPlacesSearchRoute: ApiPlacesSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
